version: '3'

services:
  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: projet_devops
    ports:
      - 3306:3306

    networks:
     - backendNetwork

  spring-boot-ems:
    image: fatimetouu19/devops_project1
    ports:
      - 8089:8089
    depends_on:
      - database

    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldatabase:3306/projet_devops?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.show-sql" : "true",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
          }'
    networks:
      - backendNetwork


networks:
  backendNetwork:
